/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistemacademico;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Panel extends javax.swing.JFrame {

    private int cantidadMn;
    private int cantidadMy;
    private int cantidadAm;
    private int arrayMenores[];
    private int arrayMayores[];
    private int arrayAdultoM[];
    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        create = new javax.swing.JButton();
        consult = new javax.swing.JButton();
        Cantidad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        create.setText("CREAR");
        create.setEnabled(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        consult.setText("CONSULTAR");
        consult.setEnabled(false);
        consult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultActionPerformed(evt);
            }
        });

        Cantidad.setText("CANTIDAD");
        Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(consult, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consult, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultActionPerformed
       String mensaje = "";
       mensaje += "menores de edad:";
       
        for (int i = 0; i < arrayMenores.length; i++) {
            mensaje += arrayMenores[i] + ",";
        }
        System.out.println("\n");
        
       mensaje+= "mayores de edad:";
        for (int i = 0; i < arrayMayores.length; i++) {
            mensaje += arrayMayores.length;
            
        }
        System.out.println("\n");
        mensaje += "adultos mayores:";
        for (int i = 0; i < arrayAdultoM.length; i++) {
            mensaje += arrayAdultoM.length;
        }
        JOptionPane.showMessageDialog(rootPane,mensaje);
        
        
        
    }//GEN-LAST:event_consultActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
    
        int arrayMenores[] = new int[cantidadMn];
      int arrayMayores[] = new int[cantidadMy];
      int arrayAdultoM[] = new int[cantidadAm];
    int menoresNum = 0;
    int mayoresNum = 0;
    int adultosMayoresNum = 0;
        
        try{
            
            while (true) {
        int edad = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Introduce tu edad:"));

        if (edad < 18) {
            if (menoresNum < arrayMenores.length) {
                arrayMenores[menoresNum] = edad;
                menoresNum++;
                JOptionPane.showMessageDialog(rootPane, "Eres menor de edad.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "El array de menores está lleno. No puedes agregar más.");
            }
        } else if (edad >= 18 && edad < 60) {
            if (mayoresNum < arrayMayores.length) {
                arrayMayores[mayoresNum] = edad;
                mayoresNum++;
                JOptionPane.showMessageDialog(rootPane, "Eres mayor de edad.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "El array de mayores está lleno. No puedes agregar más.");
            }
        } else if (edad >= 60) {
            if (adultosMayoresNum < arrayAdultoM.length) {
                arrayAdultoM[adultosMayoresNum] = edad;
                adultosMayoresNum++;
                JOptionPane.showMessageDialog(rootPane, "Eres adulto mayor.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "El array de adultos mayores está lleno. No puedes agregar más.");
            }
        }
        consult.setEnabled(true);
        }
        
        }catch(NumberFormatException e){
        
                        JOptionPane.showMessageDialog(rootPane, "solo se recibe numeros enteros");

        }
       
        
    }//GEN-LAST:event_createActionPerformed

    private void CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadActionPerformed
        
     try{
     cantidadMn = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "ESCRIBE LA CANTIDAD DE PERSONAS PARA PERSONAS MENORES"));
        cantidadMy = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "ESCRIBE LA CANTIDAD DE PERSONAS PARA PERSONAS MAYORES"));
        cantidadAm = Integer.parseInt(JOptionPane.showInputDialog(rootPane, "ESCRIBE LA CANTIDAD DE PERSONAS PARA PERSONAS ADULTOS MAYOR"));

        arrayMenores = new int[cantidadMn];
        arrayMayores = new int[cantidadMy];
        arrayAdultoM = new int[cantidadAm];

        create.setEnabled(true);
        consult.setEnabled(false);
     }catch(NumberFormatException e){
     
                             JOptionPane.showMessageDialog(rootPane, "solo se recibe numeros enteros");

     }
    }//GEN-LAST:event_CantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        int arrayMenores[];
      int arrayMayores[];
      int arrayAdultoM[]; 
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cantidad;
    private javax.swing.JButton consult;
    private javax.swing.JButton create;
    // End of variables declaration//GEN-END:variables
}
